### DISCUSSION TITLE
Interrupts

### DISCUSSION THREAD

**Discussion by flyte** [flyte/mqtt-io#179] [General]
There was a good discussion in #53 and some more in #146 about how to handle interrupts. Some questions were raised; should we:

- Send an interrupt_payload on any interrupt, ignoring the value of the pin?
- Poll the pin to get the latest value when an interrupt is fired?
- Use another module to raise an interrupt by connecting an interrupt output from one module to an interrupt input on another?

On the new asyncio version #178 I've written, I've tried to make the best of all scenarios, as explained in [the wiki](https://github.com/flyte/pi-mqtt-gpio/wiki/Asyncio-Interrupts), but there will still be scenarios that don't work, so let's discuss those here.

**Comment by mschlenstedt** [comment]
Maybe a stupid question... ;-) is that interrupt thing already working? I am not sure if it is already implemented - some documents here say "no, we are waiting for the asyncio branch", some already explain the configuration: https://mqtt-io.app/2.2.6/#/config/interrupts

**Comment by jjarokergc** [comment]
@flyte 

Ellis, 
Thank you for the MCP23017 interrupt handling.  I have just finished testing it with 3 chips and 16 inputs.  The wiring is similar to your drawing, copied below.  

![pimcp](https://user-images.githubusercontent.com/1794056/134605640-27e7dd56-0f42-4c1b-910a-65ecc60ddd4d.png)

Here is the config file with suggestions, in case it helps anyone with the setup.  

- The MCP23017 interrupt pins (A and B) are connected to the RPI's gpio pins.  Both interrupts must be connected because Int_A is for MCP23017 pins (0..7) and Int_B is for pins (8..15).
- The mosquito broker runs on the homeassistant host.  The user credentials are copied into the mqtt_io config file in plain text.  It would be nice to use a secrets file, instead.
- Configure the devices using ha_discovery options in the mqtt_io config file (instead of in home assistant).  This saves a lot of time and can be reproduced easily.
- I ran mqtt_io as a regular user 'mqtt'

Best regards,
Jon

```
# Configuration file for mqtt-io operating on rpiBE01 host
# - Connecting wired sensors and outputs to mqtt
# - Communicating with homeassitant operating on rpiFE01 host

mqtt:
  host: homeassistant.local
  user: mqttuser              # User created on homeassistant.local
  password: x
  topic_prefix: rpiBE01       # Prefix to prepend to every topic to differentiate instances of the software connecting to the same MQTT server.
  ha_discovery:               # MQTT IO will send an announcement to Home Assistant to notify it of the devices that have been exposed.
    enabled: yes
    name: "rpiBE01"           # Name of this device as it appears in homeassistant
  # Home Assistant's availability checking rquires two values
  status_payload_running: online
  status_payload_stopped: offline
  status_payload_dead: offline

###############
## GPIO MODULES
###############
gpio_modules:
  # RPIs built-in I/O
  - name: rpibe01             # Friendly name for the module used in the "digital_input" and "digital_output" configurations
    module: raspberrypi       # Type of GPIO module used (raspberrypi, pcf8574 etc.) for this configuration.

  # Custom General Purpose I/O Board
  - name: IO_20
    module: mcp23017
    chip_addr: 0x20           # i2c Address for Module
  - name: IO_21
    module: mcp23017
    chip_addr: 0x21             
  - name: IO_22
    module: mcp23017
    chip_addr: 0x22             
  # - name: IO_23
  #   module: mcp23017
  #   chip_addr: 0x23             



###############
## INPUTS
###############
digital_inputs:

  ### INTERRUPT PINS
  - name: IO_20_IntA
    module: rpibe01
    pin: 20
    interrupt: falling
    inverted: yes
    ha_discovery:
      component: binary_sensor
      name: Interrupt - IO_20 A
    interrupt_for: 
      - glassDining_Room
      - motionDining_Room
      - glassLiving_Room
      - motionLiving_Room_Closet
      - motionSide_Entry
      - glassSide_Entry
      - motionLiving_Room_Entry
      - glassKitchen

  - name: IO_20_IntB
    module: rpibe01
    pin: 21
    interrupt: falling
    inverted: yes
    ha_discovery:
      component: binary_sensor
      name: Interrupt - IO_20 B
    interrupt_for: 
      - motionRec_Room_Window
      - glassRec_Room_Window
      - motion2Nd_Fl_Hallway
      - motionKitchen_Door
      - motionRec_Room_Wall
      - glassRec_Room_Wall
      - motionVestibule
      - glassVestibule

  - name: IO_21_IntB
    module: rpibe01
    pin: 25
    interrupt: falling
    inverted: yes
    ha_discovery:
      component: binary_sensor
      name: Interrupt - IO_21 B
    interrupt_for: 
      - doorSide
      - doorFront
      - doorBack
      - motionFamily_Room

  # - name: IO_22_IntA
  #   module: rpibe01
  #   pin: 17
  #   interrupt: falling
  #   inverted: yes
  #   ha_discovery:
  #     component: binary_sensor
  #     name: Interrupt - IO_22 A
  #   interrupt_for: 


  ### GPIO MODULE PINS
  - name: glassDining_Room
    module: IO_20
    pin: 0    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Glass Break - Dining Room
      device_class: sound
      icon: mdi:vibrate

  - name: motionDining_Room
    module: IO_20
    pin: 1    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Dining Room
      device_class: motion
      icon: mdi:motion-sensor

  - name: glassLiving_Room
    module: IO_20
    pin: 2    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Glass Break - Living Room
      device_class: sound
      icon: mdi:vibrate

  - name: motionLiving_Room_Closet
    module: IO_20
    pin: 3    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Living Room Closet
      device_class: motion
      icon: mdi:motion-sensor

  - name: motionSide_Entry
    module: IO_20
    pin: 4    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Side Entry
      device_class: motion
      icon: mdi:motion-sensor

  - name: glassSide_Entry
    module: IO_20
    pin: 5    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Glass Break - Side Entry
      device_class: sound
      icon: mdi:vibrate

  - name: motionLiving_Room_Entry
    module: IO_20
    pin: 6    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Living Room Entry
      device_class: motion
      icon: mdi:motion-sensor

  - name: glassKitchen
    module: IO_20
    pin: 7    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Glass Break - Kitchen
      device_class: sound
      icon: mdi:vibrate

  - name: motionRec_Room_Window
    module: IO_20
    pin: 8    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Rec Room Window
      device_class: motion
      icon: mdi:motion-sensor

  - name: glassRec_Room_Window
    module: IO_20
    pin: 9    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Glass Break - Rec Room Window
      device_class: sound
      icon: mdi:vibrate

  - name: motion2Nd_Fl_Hallway
    module: IO_20
    pin: 10    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - 2nd Fl Hallway
      device_class: motion
      icon: mdi:motion-sensor

  - name: motionKitchen_Door
    module: IO_20
    pin: 11    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Kitchen Door
      device_class: motion
      icon: mdi:motion-sensor

  - name: motionRec_Room_Wall
    module: IO_20
    pin: 12    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Rec Room Wall
      device_class: motion
      icon: mdi:motion-sensor

  - name: glassRec_Room_Wall
    module: IO_20
    pin: 13    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Glass Break - Rec Room Wall
      device_class: sound
      icon: mdi:vibrate

  - name: motionVestibule
    module: IO_20
    pin: 14    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Vestibule
      device_class: motion
      icon: mdi:motion-sensor

  - name: glassVestibule
    module: IO_20
    pin: 15    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Glass Break - Vestibule
      device_class: sound
      icon: mdi:vibrate

  - name: doorSide
    module: IO_21
    pin: 12    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Door Contact - Side
      device_class: door
      icon: mdi:door

  - name: doorFront
    module: IO_21
    pin: 13    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Door Contact - Front
      device_class: door
      icon: mdi:door

  - name: doorBack
    module: IO_21
    pin: 14    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Door Contact - Back
      device_class: door
      icon: mdi:door

  - name: motionFamily_Room
    module: IO_21
    pin: 15    
    on_payload: "ON"
    off_payload: "OFF"
    inverted: yes
    pullup: yes
    pulldown: no
    retain: yes
    interrupt: both
    ha_discovery:
      component: binary_sensor
      name: Motion - Family Room
      device_class: motion
      icon: mdi:motion-sensor

###############
## OUTPUTS
###############
digital_outputs:

  - name: sirenHallway-Warble
    module: IO_22
    pin: 3
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
    publish_initial: yes
    retain: yes
    ha_discovery:
      component: switch
      name: Siren - Hallway Warble
      icon: mdi:alarm-bell
  # - name: sirenHallway-Steady
  #   module: IO_22
  #   pin: 1    
  #   on_payload: "ON"
  #   off_payload: "OFF"
  #   pullup: yes
  #   pulldown: no
  #   retain: yes
  #   interrupt: both
  #   ha_discovery:
  #     component: binary_sensor
  #     name: Siren - Hallway-Steady
  #     device_class: siren
  #     icon: mdi:alarm-bell

###############
## LOGGING
###############
logging:
  version: 1
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
  formatters:
    default:
      format: "%(asctime)s %(name)s [%(levelname)-8s] %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  loggers:
    mqtt_io:
      level: DEBUG
      handlers:
        - console
      propagate: yes
    asyncio:
      level: DEBUG
      handlers:
        - console
      propagate: yes
```
