### DISCUSSION TITLE
unknown field in config

### DISCUSSION THREAD

**Discussion by claudegel** [flyte/mqtt-io#245] [Q&A] [answered]
I'm building a new gpio module for dockerpi 4 channel relay. For this I need two parameters dev_addr and i2c_bus_num.
I've added in my module the following:
```
CONFIG_SCHEMA = {
    "i2c_bus_num": {
        "type": "integer",
        "required": True,
        "empty": False,
        "default": 1,
    }, 
    "dev_addr": {
        "type": "integer",
        "required": True,
        "empty": False,
        "default": 11,
    }, # 0x10, 0x11, 0x12, 0x13
}
```
But when I run python3 -m mqtt_io /home/pi/config.yml
I get the following error
```
mqtt_io.exceptions.ConfigValidationFailed: Config did not validate:
dev_addr:
- unknown field
i2c_bus_num:
- unknown field 
```
in my config.yml I have:
```
...
gpio_modules:
  - name: raspberrypi
    module: raspberrypi
  - name: dockerpi
    module: dockerpi

digital_outputs:
  - name: toit_toggle
    module: raspberrypi
    pin: 23
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
    retain: yes
    
  - name: toit_spa_2
    module: dockerpi
    i2c_bus_num: 1
    dev_addr: 0x11
    pin: 1
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
    retain: yes

```
How can I add new config name in config.yml other then the one you have. Other modules have specific config  with CONFIG_SCHEMA
but I can't figure out where to go
