### DISCUSSION TITLE
Digital outputs not publishing

### DISCUSSION THREAD

**Discussion by bsmith76s** [flyte/mqtt-io#272] [Q&A]
I have been struggling with this for days. Installed MQTT-IO on a RPI0W and have the digital inputs publishing to broker. I can see them in MQTT explorer. But I can not seem to get digital outputs to publish to broker and not seeing them in MQTT Explorer. Tried changing config.yml many times but I must be overlooking something. Here is a sample of my config.yml

```
mqtt:
  host: 10.10.51.10
  port: 1883
  user: "mqtt"
  password: "xxxxxxx"
  topic_prefix: pimqtt/house_garage
  status_topic: status
  status_payload_running: online
  status_payload_stopped: offline
  status_payload_dead: dead

gpio_modules:
  - name: raspberrypi
    module: raspberrypi

digital_outputs:
  - name: door1
    module: raspberrypi
    pin: 5
    on_payload: "ON"
    off_payload: "OFF"
    inverted: true
    initial: high
#  - name: door2
#    module: raspberrypi
#    pin: 6 #GPIO 
#    on_payload: "ON"
#    off_payload: "OFF"
#    inverted: true
#    initial: high
digital_inputs:
  - name: door1_closed
    module: raspberrypi
    pin: 22 # GPIO 
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no

```
