### ISSUE TITLE
Digital Input - Polling

### ISSUE THREAD

**Issue by barista123** [flyte/mqtt-io#116]
Is it possible to poll the status of a digital input like sensors?  I am using a couple float switches to check the status of a water tank. My front end is home assistant. When the home assistant server is restarted for updates, config changes, etc. It does not retain the last known state of the float switches and defaults to off.  If I manually trigger the switch or restart pi-mqtt-gpio the state updates correctly.

Thanks

**Comment by flyte** [comment]
You'll probably want to use `retain` for that. For example:

```yaml
digital_inputs:
  - name: water_tank
    module: whatever
    pin: 22
    on_payload: "ON"
    off_payload: "OFF"
    retain: yes
```
