### ISSUE TITLE
Initial output pin states

### ISSUE THREAD

**Issue by mr2c12** [flyte/mqtt-io#125]
Dear all,
this is quite similar to #76 but not really the same.

I think that the state of the output pins should be published at boot. Since we can configure the inital state for these pins, and the initial state could be different from the last one (e.g. pin is HIGH, restart, default LOW, pin is LOW but noone is notified), situations can occur where the known state of a pin is different from the actual one.

Any thought?

**Comment by flyte** [comment]
I've made an option to publish the value of the output on startup and added instructions to the readme (see commits above). I'm not in a position to test it out at the moment, but please let me know if it works for you if you do. Otherwise I'll test it as soon as I can, and make a new release.

**Comment by mr2c12** [comment]
Any way to get the required changes in my virtualenv+pip installation?

Edit: replaced my local folder
mqttgpio/lib/python3.7/site-packages/pi_mqtt_gpio
with content from
pi_mqtt_gpio
from the github repo.
Not working, maybe I just did something useless. Pi-mqtt-gpio starts but completely ignore the new setting:

```
digital_outputs:
  - name: pin_buzzer
    module: raspberrypi
    pin: 22
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
    retain: no
    publish_initial: yes
```

Probably my fault.
