### ISSUE TITLE
Auto start not working

### ISSUE THREAD

**Issue by claudegel** [flyte/mqtt-io#129]
I've added to /etc/rc.local just before the last line exit 0
`python -m pi_mqtt_gpio.server /home/pi/config.yml &`
to have the program started automatically. But it fail somehow.
If I start it manually with 
`python -m pi_mqtt_gpio.server /home/pi/config.yml`
It work ok
Where can I check to find out what is going wrong ?
My config
```
mqtt:
  host: 192.168.20.178
  port: 1883
  user: "user"
  password: "passwd"
  topic_prefix: solarium

gpio_modules:
  - name: raspberrypi
    module: raspberrypi

digital_outputs:
  - name: toit_spa
    module: raspberrypi
    pin: 18
    on_payload: "ON"
    off_payload: "OFF"
    initial: low # low or high
    retain: yes

  - name: toit_solarium
    module: raspberrypi
    pin: 17
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
    retain: yes

  - name: toit_toggle
    module: raspberrypi
    pin: 23
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
    retain: yes

digital_inputs:
  - name: rain
    module: raspberrypi
    pin: 22
    on_payload: "on"
    off_payload: "off"
    pullup: yes
    pulldown: no
```
