### ISSUE TITLE
Digital outputs multiple pin, same topic

### ISSUE THREAD

**Issue by terminet85** [flyte/mqtt-io#136]
There is any change to turn on/off multiple pin with the same mqtt topic?

RPi.GPIO module should be able to manage it
`chan_list = [11,12]    # add as many channels as you want!
                       # you can tuples instead i.e.:
                       #   chan_list = (11,12)
GPIO.setup(chan_list, GPIO.OUT)
`

**Comment by terminet85** [comment]
I've made a PR in order to fix schema check. 
RPi.GPIO  are already capable to manage lists, so the problem was only in the config check.

```yaml
digital_outputs:
  - name: fireplace
    module: raspberrypi
    pin:
       - 17
       - 27
       - 22
       - 5
```
