### ISSUE TITLE
Feature request: could you add support for ADS1115 analog/digital converter ?

### ISSUE THREAD

**Issue by tkranz** [flyte/mqtt-io#144]
I see there is support for MPC3008, is it possible to add ADS115 as well ?

thanks
Thomas

**Comment by BenjiU** [comment]
Hi,

may you check my implementation on branch `feature/ADS1115`? I don't have the chip here, so i can't test it.

```
mqtt:
  host: mqtt
  port: 1883
  user: ""
  password: ""
  topic_prefix: topic

sensor_modules:
  - name: ads1115_sensor
    module: ads1115

sensor_inputs:
  - name: ads1115_voltage
    module: ads1115_sensor
    interval: 20  # measurement every 20sec
    channel: CH0 # measure on CH0 of ADS1115
```
