### ISSUE TITLE
Could not find sensor of type DS18S20 with id XYZ

### ISSUE THREAD

**Issue by Maerchensarg** [flyte/mqtt-io#156]
Hi. Thanks for this great project. Somehow I don't understand something or run into a mistake somewhere else. I am trying to connect a 1-wire temperature sensor.
```
pi@raspberrypi:~ $ cat /sys/bus/w1/devices/28-01131e858aef/w1_slave
  48 01 4b 46 7f ff 0c 10 96 : crc=96 YES
  48 01 4b 46 7f ff 0c 10 96 t=20500
```

```yaml
sensor_modules:
  - name: ds18b22_sensor
    module: ds18b
    type: DS18S20
    address: 01131e858aef

sensor_inputs:
  - name: ds18b22_temperature
    module: ds18b22_sensor
    interval: 10
    digits: 2
```

```
Error:
  Could not find sensor of type DS18S20 with id 01131e858aef
  Please check cabling and check your /boot/config.txt for
  dtoverlay=w1-gpio
```

My config includes the above adjustment. Any idea what is missing?
