### ISSUE TITLE
CONFIG_SCHEMA is missing payload defaults in digital_outputs node

### ISSUE THREAD

**Issue by robbyb67** [flyte/mqtt-io#159]
- [x] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Github Wiki](https://github.com/flyte/pi-mqtt-gpio/wiki) to see if the information there helps.

**Describe the bug**
Runtime error occurs in logging message if payload_on and payload_off are not configured for digital outputs

**Expected behavior**
"ON" and "OFF" should be used as default payload for digital outputs when nothing is configured.

**Error messages and traceback**
```
(ERROR): Exception while handling received MQTT message:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pi_mqtt_gpio/server.py", line 528, in on_msg
    handle_set(topic_prefix, msg)
  File "/usr/local/lib/python2.7/dist-packages/pi_mqtt_gpio/server.py", line 221, in handle_set
    if payload not in (output_config["on_payload"], output_config["off_payload"]):
KeyError: 'on_payload'
```

**Config**
```yaml
  host: mqtt
  port: 1883
  client_id: pi-mqttXXX
  user: ""
  password: ""
  topic_prefix: /oh3/

gpio_modules:
  - name: piface
    module: piface2

digital_inputs:
  - name: carport_contact
    module: piface
    pin: 7

digital_outputs:
  - name: carport_close_trigger
    module: piface
    pin: 7

```

**Hardware**
 - Platform: Raspberry Pi
 - Connected hardware:  piface2

**System:**
 - OS: Raspbian
 - Python version: Python 2.7.9
 - User you're running as: root
 - Using a virtualenv?: no

**Additional context**
I think there are simply two lines missing in __init__.py:
default "ON" between 264/265
default "OFF" between 268/269
