### ISSUE TITLE
Change of pin numbering?

### ISSUE THREAD

**Issue by MTJoker** [flyte/mqtt-io#191]
Hi,
I have been using pi-mqtt-gpio since a longer time now and wanted to change to the new mqtt-io. I am using the piface2 module. 
Was there a change regarding the pin numbering? In my old configuration, I had for example:

```
digital_inputs:
  - name: bellbutton_garden
    module: piface
    pin: 0
    on_payload: "on"
    off_payload: "off"
    pullup: yes
    pulldown: no

digital_outputs:
  - name: bellrelay
    module: piface
    pin: 0
    timed_set_ms: 500
    on_payload: "on"
    off_payload: "off"
```
Now this previously working configuration gives the following error:
```
Config did not validate due to errors in the following sections:
gpio_modules:
  piface:
  - Pin '0' has more than one configuration in digital_inputs or digital_outputs
```

Is this the intended behavior? If yes, then how are the pins of the piface2 module numbered now? In the documentation of the pifacedigitalio python module, it seems that the same pin numbers are available as input and output, e.g. output_pins[0..7] and input_pins[0..7].
