### ISSUE TITLE
There is no current event loop in thread 'Dummy-1'

### ISSUE THREAD

**Issue by fipwmaqzufheoxq92ebc** [flyte/mqtt-io#198]
- [x] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Github Wiki](https://github.com/flyte/pi-mqtt-gpio/wiki) to see if the information there helps.

**Describe the bug**
When using interrupts and the "raspberrrypi" module, no messages are published, but an error message is logged (see below).

**Expected behavior**
No error message and a MQTT message is published

**Error messages and traceback**
```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mqtt_io/server.py", line 786, in interrupt_callback
    self.event_bus.fire(DigitalInputChangedEvent(pin_name, None, value))
  File "/usr/local/lib/python3.7/site-packages/mqtt_io/events.py", line 112, in fire
    fut: "asyncio.Future[asyncio.Task[Any]]" = asyncio.Future()
  File "/usr/local/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Dummy-1'.
```

**Config**
```yaml
mqtt: [...]

gpio_modules:
  - name: pi_gpio
    module: raspberrypi
    cleanup: yes

digital_outputs:
  - name: led
    module: pi_gpio
    pin: 20

digital_inputs:
  - name: light_sensor
    module: pi_gpio
    pin: 12
    interrupt: both
  - name: motion
    module: pi_gpio
    pin: 21
    interrupt: both
    bouncetime: 1000

logging:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s %(name)s (%(levelname)s): %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    mqtt_gpio:
      level: DEBUG
      handlers: [ console ]
      propagate: yes
```

**Hardware**
 - Platform: Raspberry Pi
 - Connected hardware:  -

**System:**
 - OS: Docker container with alpine-linux / Host is Raspbian
 - Python version: Python 3.7.10  (also tried 3.8)
 - User you're running as: root
 - Using a virtualenv?: no

**Additional context**
I think it happens because RPi.GPIO calls the callback on a separate thread ([Ref](https://sourceforge.net/p/raspberry-gpio-python/wiki/Inputs/) # Threaded callbacks)
