### ISSUE TITLE
Sensor DHT22 and loggin do not work in 2.2.6, works ok in 0.5.6

### ISSUE THREAD

**Issue by mihadoo** [flyte/mqtt-io#229]
- [x] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Documentation](https://mqtt-io.app/) to see if the information there helps.

**Describe the bug**
DHT22 sensor does not work on Raspberry Pi 3B

**Expected behavior**
The mqtt-io.yml below does not work. GPIO seems to work, however DHT22 sensor does not work.  On 0.5.6 it works correctly. On 0.5.6 when DHT22 was not connected to the Pi then an error was displayed after the interval. In 2.2.6 simply nothing happens, as if the sensor is not configured at all.

**Error messages and traceback**

The only output I get is for GPIO, nothing for DHT22:

```
2021-05-30 21:46:15 mqtt_io.server [INFO] Connecting to MQTT...
2021-05-30 21:46:15 mqtt_io.server [INFO] Digital input 'doorbell' value changed to False
2021-05-30 21:46:15 mqtt_io.server [INFO] Connected to MQTT
```

**Config**
```yaml
mqtt:
  host: 192.168.218.21
  port: 1883
  user: "openhabian"
  password: "something"
  topic_prefix: bridge/t15/raspi3/gpio

# GPIO
gpio_modules:
  # Use the Raspberry Pi built-in GPIO
  - name: rpi
    module: raspberrypi

digital_inputs:
  # Pin 0 is an input connected to a doorbell button
  - name: doorbell
    module: rpi
    pin: 14

sensor_modules:
  - name: dht22
    module: dht22
    type: DHT22 # can be  DHT11, DHT22 or AM2302
    pin: 15

sensor_inputs:
  - name: ffsalontemperature
    module: dht22
    interval: 5 #interval in seconds, that a value is read from the sensor and a update is published
    digits: 4 # number of digits to be round
    type: temperature # Can be temperature or humidity

  - name: ffsalonhumidity
    module: dht22_sensor1
    interval: 5 #interval in seconds, that a value is read from the sensor and a update is published
    digits: 4 # number of digits to be round
    type: humidity # Can be temperature or humidity
```

**Hardware**
 - Raspberry Pi 3B
 - DHT22

**System:**
 - OS: latest rapsbian
 - Python version: 3.7.3
 - User you're running as: pi
 - Using a virtualenv?: no

**Additional context**
If I add the following to the yaml then I get no output at all. This works correctly in 0.5.6 but not in 2.2.6:

```
logging:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s %(name)s (%(levelname)s): %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
    file:
      class : logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: /home/pi/log_pi_mqtt_gpio.log
      maxBytes: 100000
      backupCount: 3
  loggers:
    mqtt_gpio:
      level: INFO
      handlers: [console,file]
      propagate: yes
```
