### ISSUE TITLE
modules pcf8574/5 always use pullups

### ISSUE THREAD

**Issue by IlmLV** [flyte/mqtt-io#233]
- [x] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Documentation](https://mqtt-io.app/) to see if the information there helps.

**Describe the bug**
Currently I am not able to NOT use pullups for pcf8574 and pcf8575 modules, because of invalid if statement [#1](https://github.com/flyte/mqtt-io/blob/6297a22f1200a35f890c2487428ee84ab2c671cd/mqtt_io/modules/gpio/pcf8574.py#L38) and [#2](https://github.com/flyte/mqtt-io/blob/6297a22f1200a35f890c2487428ee84ab2c671cd/mqtt_io/modules/gpio/pcf8575.py#L38) which could never be satisfied.
`pullup is not None` - looks like this statement is left unchanged when code was refactored to use pullup_maps, as only `self.pullup_map[pullup]` can be null.

**Expected behavior**
If digital_input has no pullup defined, then no pullup should be made as it breaks digital_input state readings.

**Config**
```yaml
mqtt:
  [...]

gpio_modules:
  - name: pcf_1
    module: pcf8574
    i2c_bus_num: 1
    chip_addr: 0x22
    cleanup: False

digital_inputs:
  - name: master_bedroom_balcony_door
    module: pcf_1
    pin: 6
    on_payload: "OPEN"
    off_payload: "CLOSED"
    retain: yes
```

**Hardware**
 - Platform: Raspberry Pi 4
 - Connected hardware: pcf8574

**System:**
 - OS: Raspbian using docker custom build image
 - Python version: Python 3.9.4
 - User you're running as: pi
 - Using a virtualenv?: no
