### ISSUE TITLE
High CPU load in polling mode (40-60%)

### ISSUE THREAD

**Issue by hacker-cb** [flyte/mqtt-io#236]
**Describe the bug**

I'm running mqtt-io on  Amlogic A113X in polling mode (CPU does not support interrupts) and it take around 40-60% CPU load

**Expected behavior**

Expect CPU load around 1-2%

**Config**
```yaml
mqtt:
  host: x.x.x.x
  user: xxxx
  password: xxxx
  topic_prefix: mqtt-io
  ha_discovery:
    enabled: yes

# GPIO
gpio_modules:
    - name: gpio
      module: gpiod

digital_inputs:
    - name: button
      module: gpio
      pin: 10
      poll_interval: 0.1
      ha_discovery:
           component: binary_sensor
           name: GPIO Button

    - name: input1
      module: gpio
      pin: 46
      poll_interval: 0.1
      ha_discovery:
           component: binary_sensor
           name: GPIO Input1
    - name: input2
      module: gpio
      pin: 45
      poll_interval: 0.1
      ha_discovery:
           component: binary_sensor
           name: GPIO Input2
    - name: input3
      module: gpio
      pin: 44
      poll_interval: 0.1
      ha_discovery:
           component: binary_sensor
           name: GPIO Input3
    - name: input4
      module: gpio
      pin: 43
      poll_interval: 0.1
      ha_discovery:
           component: binary_sensor
           name: GPIO Input4

digital_outputs:
    - name: output1
      module: gpio
      pin: 30
      initial: low
      publish_initial: true
      ha_discovery:
          component: switch
          name: GPIO Output1
    - name: output2
      module: gpio
      pin: 29
      initial: low
      publish_initial: true
      ha_discovery:
          component: switch
          name: GPIO Output2
    - name: output3
      module: gpio
      pin: 28
      initial: low
      publish_initial: true
      ha_discovery:
          component: switch
          name: GPIO Output3
```

**Hardware**
 - Platform: Amlogic A113X (ARM Cortex-A53) quad-core up to 1.5GHz
 - Connected hardware: none

**System:**
 - OS: Armbian aarch64
 - Python version: Python 3.8.10
 - User you're running as: root
 - Using a virtualenv?: no

**Comment by Torxgewinde** [comment]
Hello, I can report of the same issue with Raspberry Pi:

As you can see the CPU usage is high and the RAM consumption is growing over time:
![Bildschirmfoto_2021-10-05_18-15-11](https://user-images.githubusercontent.com/12876583/136062436-c99b1114-aad3-42f8-8dc1-603e1cef9d77.png)
![Bildschirmfoto_2021-10-05_18-17-43](https://user-images.githubusercontent.com/12876583/136062626-6a4b3316-0c27-4fe7-a534-68dbf3ddeca3.png)

I confirmed that mqtt-io is the process consuming all that RAM and causing about 40-50% CPU load by logging into the RPi and checking with `htop`. Killing the process dropped both values to nearly 1-3%.

### Config
```
mqtt:
  host: xxx
  port: 8883
  user: xxx
  password: xxx
  topic_prefix: wohnzimmer
  reconnect_delay: 5
  reconnect_count: 999
  ha_discovery:
    enabled: no
  tls:
    enabled: yes
    ca_certs: /root/xxx1.crt
    certfile: /root/xxx2.crt
    keyfile: /root/xxx.pem

gpio_modules:
  - name: rpi
    module: raspberrypi
    cleanup: true

digital_inputs:
  - name: Schalter_01
    module: rpi
    pin: 14
    on_payload: "on"
    off_payload: "off"
    pulldown: true
    retain: true
    poll_interval: 0.1

  - name: Schalter_02
    module: rpi
    pin: 15
    on_payload: "on"
    off_payload: "off"
    pulldown: true
    retain: true
    poll_interval: 0.1

  - name: Schalter_03
    module: rpi
    pin: 23
    on_payload: "on"
    off_payload: "off"
    pulldown: true
    retain: true
    poll_interval: 0.1

  - name: Schalter_04
    module: rpi
    pin: 18
    on_payload: "on"
    off_payload: "off"
    pulldown: true
    retain: true
    poll_interval: 0.1

digital_outputs:
#1
  - name: xxx01
    module: rpi
    pin: 11
    initial: "low"
    publish_initial: true
    retain: true

#2
  - name: xxx02
    module: rpi
    pin: 17
    initial: "low"
    publish_initial: true
    retain: true

#3
  - name: xxx03
    module: rpi
    pin: 22
    initial: "low"
    publish_initial: true
    retain: true

#4
  - name: xxx04
    module: rpi
    pin: 9
    initial: "low"
    publish_initial: true
    retain: true

#5  
  - name: xxx05
    module: rpi
    pin: 10
    initial: "low"
    publish_initial: true
    retain: true

#6
  - name: xxx06
    module: rpi
    pin: 24
    initial: "low"
    publish_initial: true
    retain: true

#7
  - name: xxx07
    module: rpi
    pin: 7
    initial: "low"
    publish_initial: true
    retain: true

#8
  - name: xxx08
    module: rpi
    pin: 25
    initial: "low"
    publish_initial: true
    retain: true

#9
  - name: xxx09
    module: rpi
    pin: 8
    initial: "low"
    publish_initial: true
    retain: true

#10  
  - name: xxx10
    module: rpi
    pin: 27
    initial: "low"
    publish_initial: true
    retain: true

#11 
  - name: xxx11
    module: rpi
    pin: 2
    initial: "low"
    publish_initial: true
    retain: true

#12 
  - name: xxx12
    module: rpi
    pin: 3
    initial: "low"
    publish_initial: true
    retain: true
 
 #13
  - name: xxx13
    module: rpi
    pin: 4
    initial: "low"
    publish_initial: true
    retain: true
```

### Hardware:
* Platform: Raspberry Pi 1B
* connected hardware: input and output relais

### System:
* OS: OpenWRT 21.02 (Linux Wohnzimmer 5.4.143 #0 Tue Aug 31 22:20:08 2021 armv6l GNU/Linux) & Debian Bullseye Chroot
* Python version: Python 3.9.2
* User: root
* virtualenv: no

Especially the growing consumption of RAM is a concern, I assume there is a memory leak or more likely a circle reference confusing the garbage collector.

### Expected behavior
Polling by a [single-configuration-script](https://github.com/Torxgewinde/MQTT-GPIO/blob/main/MQTT_GPIO.py), resembling similar behavior to the configuration above, takes about **3-4% CPU and 3-4% of RAM**, so there is substantial overhead:
![Bildschirmfoto_2021-10-09_09-41-14](https://user-images.githubusercontent.com/12876583/136649239-ccf12258-7b18-45cd-8768-25056430e35e.png)
I would expect mqtt-io to consume just a little bit more RAM and CPU since it is a lot more versatile.

Edit: Wrote a script to check how low the RAM and CPU could be to narrow down what might be the issue.

**Comment by MrC0nst** [comment]
Same issue, 55-65% CPU load

**Comment by griesi** [comment]
Hi there, I got the same issue on a fresh install 

### Hardware

- Raspberry Pi 1B
- Piface Digital (Version 1)

### System

- OS: Raspberry OS (2021-10-30-raspios-bullseye-armhf-lite)
- Python Version 3.9.2
- User: pi / same behaviour when starting as root with supervisor

**mqtt-io starting takes about 1-2 minutes (90-100% CPU load) and then takes about 70% CPU load**

`/usr/bin/python3 -m mqtt_io /home/pi/mqtt_io/config.yml`

### Config


```
mqtt:
  host: smarthome.local
  port: 8883
  user: mqtt-heaterpi
  topic_prefix: heaterpi/piface
  tls:
    enabled: true
    ca_certs: /home/pi/mqtt_io/iobroker_ca.crt
    certfile: /home/pi/mqtt_io/mqtt-heaterpi.crt
    keyfile: /home/pi/mqtt_io/mqtt-heaterpi.key
gpio_modules:
  - name: piface2
    module: piface2
digital_inputs:
  - name: input_1
    module: piface2
    pin: 0
  - name: input_2
    module: piface2
    pin: 1
  - name: input_3
    module: piface2
    pin: 2
  - name: input_4
    module: piface2
    pin: 3
  - name: input_5
    module: piface2
    pin: 4
  - name: input_6
    module: piface2
    pin: 5
  - name: input_7
    module: piface2
    pin: 6
  - name: input_8
    module: piface2
    pin: 7
digital_outputs:
  - name: output_1
    module: piface2
    pin: 0
  - name: output_2
    module: piface2
    pin: 1
  - name: output_3
    module: piface2
    pin: 2
  - name: output_4
    module: piface2
    pin: 3
  - name: output_5
    module: piface2
    pin: 4
  - name: output_6
    module: piface2
    pin: 5
  - name: output_7
    module: piface2
    pin: 6
  - name: output_8
    module: piface2
    pin: 7
```

mqtt-io works as expected

**Comment by monte-monte** [comment]
Try disabling logging, or set it to higher level like this:
```
logging:
  version: 1
  loggers:
    mqtt_gpio:
      level: WARN
```
It helped me to bring CPU usage of mqqt_io to below 10%.

**Comment by hacker-cb** [comment]
> Try disabling logging, or set it to higher level like this:
> 
> ```
> logging:
>   version: 1
>   loggers:
>     mqtt_gpio:
>       level: WARN
> ```
> 
> It helped me to bring CPU usage of mqqt_io to below 10%.

Nothing was changed in CPU load. It is still around 50% of one core.

**Comment by griesi** [comment]
> Try disabling logging, or set it to higher level like this:
> 
> ```
> logging:
>   version: 1
>   loggers:
>     mqtt_gpio:
>       level: WARN
> ```
> 
> It helped me to bring CPU usage of mqqt_io to below 10%.

Sorry, CPU-Load is still around 70-80% on my setup.

@monte-monte Are you sure with that syntax? Shouldn't module name be 'mqtt_io' not 'mqtt_gpio'? I also tried this with no success.

**Comment by monte-monte** [comment]
@griesi yes you are right, but for some reason the way I wrote it worked too, logging stopped.
For me I see 6-12% cpu usage after restartting mqtt_io, but it gradually creeps up to 30+%. I don't know how or why.

**Comment by andystewart999** [comment]
Hi all - I don't have a particular problem with high CPU usage, but I've definitely got a memory leak.  On my Raspberry Pi Model B+ (granted, pretty old) running Raspbian 11 (Bullseye), fully patched, it's leaking about 20% per day.

![Pi_RAM](https://user-images.githubusercontent.com/18434441/153566220-ab6f1e4f-4318-4876-84ca-e67856f70de0.PNG)

![Pi_CPU](https://user-images.githubusercontent.com/18434441/153566244-14cca703-4e32-4e55-a658-6a2c4d6f031a.PNG)

Here's my config, for reference:

```
mqtt:
  host: 192.168.x.y
  port: 1883
  user: mqtt
  password: password
  topic_prefix: pi4/garage
  client_id: pi-4-mqttio
  ha_discovery:
    enabled: yes
    name: pi-4 MQTT IO

# GPIO
gpio_modules:
  # Use the Raspberry Pi built-in GPIO
  - name: rpi
    module: raspberrypi

digital_outputs:
  # GPIO 4 is connected to the garage door manual button
  - name: garage_door_4
    module: rpi
    pin: 4
    inverted: true
    retain: true
    initial: high
    ha_discovery:
      name: Garage door
      device_class: switch

  # Pin 22 is connected to the security PIR relay
  - name: garage_pir_22
    module: rpi
    pin: 22
    inverted: false
    retain: true
    ha_discovery:
      name: Garage PIR
      device_class: switch

digital_inputs:
  # Pin 19 is connected to the workshop door
  - name: workshop_door_19
    module: rpi
    pin: 19
    pullup: true
    pulldown: true
    inverted: false
    retain: true
    ha_discovery:
      name: Workshop door
      device_class: door

  # Pin 26 is connected to the garage door
  - name: garage_door_26
    module: rpi
    pin: 26
    pullup: true
    pulldown: true
    inverted: false
    retain: true
    ha_discovery:
      name: Garage door
      device_class: garage_door

```

**Comment by griesi** [comment]
Hi, after changing the hardware from Raspberry Pi 1 which is a single core system with PiFace 1 board to Raspberry Pi 2 which is a quad core system with much more compute power with PiFace 2 board the Problem with CPU usage seemed to be gone. 

I guess the hardware of that pretty old Raspberry is just too old and too weak for mqtt_io. I don't think it is about the PiFace board which imho is basically the same hardware.

Indeed I'm seeing the same issue with memory consumption of the mqtt_io process.

![image](https://user-images.githubusercontent.com/10785040/160234124-20a7ace7-39b4-42a3-8c8e-8491568ffb93.png)

I worked around this by restarting the process once a day by the supervisor daemon which is controlling the process as you can see on the image.

**Comment by griesi** [comment]
Opened a new Issue regarding the memory leak. 

In my case the issue with CPU load is resolved by changing the hardware platform from Raspberry Pi1 to Raspberry Pi2. 

@hacker-cb: What about your issue with your Amlogic A113X (ARM Cortex-A53) which should at least perform as well as the Raspberry Pi 2.

@MrC0nst @monte-monte: What kind of hardware are you using?

**Comment by MrC0nst** [comment]
Model : Raspberry Pi Model B Rev 2

**Comment by Torxgewinde** [comment]
Good idea to separate the issues of high-CPU-load and memory-leak.

As shown with [the simple script](https://github.com/Torxgewinde/MQTT-GPIO/blob/main/MQTT_GPIO.py) the old hardware itself is easily able to handle MQTT and GPIOs at a few percent CPU load. I would expect mqtt-io to be a little above such a bare minimum script, but not as much as it is right now. The first/second RPI is still "good enough" for such tasks.

I assume there must be a debugging option for Python to see which function is consuming so many CPU cycles and perhaps narrow down the memory-leak.

**Comment by markferry** [comment]
The rate at which CPU load increases over time is correlated with lower interval time.

I have two nodes (`study`, `lounge`), specs are:
 * RPi 3 model B Rev 1.2
 * kernel 4.19.122-2-osmc ([OSMC](https://osmc.tv/))
 * python 3.7.3
 * mqtt-io (2.2.6)

`pip freeze`:
```
Adafruit-DHT==1.4.0
asyncio-mqtt==0.8.1
backoff==1.11.1
Cerberus==1.3.4
memory-profiler==0.60.0
mqtt-io==2.2.6
paho-mqtt==1.6.1
pkg-resources==0.0.0
psutil==5.9.0
PyYAML==5.4.1
typing-extensions==3.10.0.2
```


![image](https://user-images.githubusercontent.com/935857/168634789-af588d80-cd69-462e-91ab-ef76a6cdc4c7.png)

On the left the CPU load on both `lounge` and `study` nodes had been climbing identically.

Around 2022-05-14 14:10:45 I set the study interval to *30s* and the lounge interval to *60s* and restarted mqtt-io on both nodes. The result is CPU load rising faster on the study node.

(Spikes in the study load ~3am are Kodi scanning for new media.)

[Interactive Grafana snapshot](https://snapshots-origin.grafana.net/dashboard/snapshot/ACajx5go15GIHMC6rLk8UYiL5H0bNRX5)

This is the config for the study node:
```yaml
mqtt:
  host: pixie3
  topic_prefix: mqtt-io/study
  ha_discovery:
    enabled: yes

sensor_modules:
  - name: dht
    module: dht22
    type: AM2302
    pin: 4

sensor_inputs:
  - name: dht_study_temperature
    module: dht
    type: temperature
    interval: 30
    ha_discovery:
      device_class: temperature
      unit_of_measurement: '°C'
  - name: dht_study_humidity
    module: dht
    type: humidity
    interval: 30
    ha_discovery:
      device_class: humidity
      unit_of_measurement: '%'

logging:
  version: 1
  loggers:
    mqtt_gpio:
      level: WARN
```
