### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Julusian** [flyte/mqtt-io#243]
- [x] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Documentation](https://mqtt-io.app/) to see if the information there helps.

**Describe the bug**
Not reconnecting to MQTT

**Expected behavior**
The software to reconnect to the MQTT server, or exit with a fatal error

**Error messages and traceback**
```
2021-12-06 00:24:39 mqtt_io.server [INFO] Digital output 'relay11' set to False (off)
2021-12-06 00:24:39 mqtt_io.server [INFO] Digital output 'relay12' set to False (off)
failed to receive on socket: [Errno 104] Connection reset by peer
```

**Config**
```yaml
mqtt:
  host: 
  port: 1883
  user: ""
  password: ""
  topic_prefix: relay/rack

gpio_modules:
  - name: raspberrypi
    module: raspberrypi

digital_outputs:
  - name: relay1
    module: raspberrypi
    pin: 2
    on_payload: "ON"
    off_payload: "OFF"

```
More outputs are defined, in an identical fashion

**Hardware**
 - Platform: Raspberry Pi 1 Model B 512MB 
 - Connected hardware:  N/A

**System:**
 - Version: 2.2.6
 - OS: Raspbian
 - Python version: 3.7.3
 - User you're running as: pi
 - Using a virtualenv?: no

**Additional context**
I believe this is also happening to some pi zeros too, but I do not have the logs to verify
