### ISSUE TITLE
Add Banana Pi/Pro Module

### ISSUE THREAD

**Issue by iamsven** [flyte/mqtt-io#28]
Hi, this project looks awesome. 
I would love to use it on my Banana Pro board. Unfortunatly I have no Python skills to implement it on my own. Therefore, I would ask you/the community to adapt the raspberry pi module to the wiriningPi library for Banana Pi/Pro 

[Official BPI-WiringPi2-Python library](https://github.com/BPI-SINOVOIP/BPI-WiringPi2-Python)

Thank you very much!

**Comment by flyte** [comment]
Hey Sven,

I'd be happy to give it a shot! I don't have the hardware but if you're willing to test it out I can probably knock something together from the docs. 

I'll let you know on here when I've got a bit of time to do it.

Cheers!

**Comment by flyte** [comment]
@iamsven Hi!

I've knocked together a module for Banana Pi from the docs. I don't know if it works or not, since I still don't have a board to test with. Would you be able to test it out for me?

You may need to become `root` for this to work, as the Banana Pi docs says it requires `root` privileges.

```bash
sudo su -
```

You'll need to clone this repository to your BPi:

```bash
git clone https://github.com/flyte/pi-mqtt-gpio.git
```

Check out the feature branch:

```bash
cd pi-mqtt-gpio
git checkout feature/bananapi
```

Make/adapt your config file, including the new `bananapi` module and pin configuration. Something like this:

```yaml
mqtt:
  host: test.mosquitto.org
  port: 1883
  user: ""
  password: ""
  topic_prefix: pimqttgpio/mydevice

gpio_modules:
  - name: bananapi
    module: bananapi

digital_inputs:
  - name: button
    module: bananapi
    pin: 21
    on_payload: "ON"
    off_payload: "OFF"
    pullup: no
    pulldown: yes

digital_outputs:
  - name: bell
    module: bananapi
    pin: 20
    on_payload: "ON"
    off_payload: "OFF"
    initial: low
```

Create a virtualenv and install requirements:

```bash
virtualenv ve
. ve/bin/activate
pip install -r requirements.txt
```

Then you should be able to run the server with:

```bash
python -m pi_mqtt_gpio.server config.yml
```

Let me know how you get on!
