### ISSUE TITLE
All relays on after restart rpi

### ISSUE THREAD

**Issue by byniow** [flyte/mqtt-io#283]
After restarting rpi i have strange behavior. My config: 

```
mqtt:
  host: 10.1.0.100
  topic_prefix: rpi_io
  user: mqtt
  password: mqtt
  ha_discovery:
    enabled: yes

# GPIO
gpio_modules:
    - name: rpi
    module: raspberrypi
digital_outputs:
  - name: P1-1
    module: rpi
    pin: 5
    inverted: True

  - name: P1-2
    module: rpi
    pin: 6
    inverted: True

  - name: P1-3
    module: rpi
    pin: 13
    inverted: True
```

And after restart i get relays on. But no in the same time, but relays are on one by one after 1 second delay. Why? i use HA to control with mosquitto, and state after rpi restart is not copied from HA, but HA show all as off. 

Second - correct config for DS18b20? I try a lot options - and no success.

**Comment by ondras12345** [comment]
Try adding `initial: high` (or `initial: low` if you want them to be on) and `publish_inital: true` to your relays.

This is my config for DS18B20:
```
sensor_modules:
  - name: dallas_a
    module: ds18b
    type: DS18B20
    address: 3c01e076877d


sensor_inputs:
  - name: temperature_a
    module: dallas_a
    interval: 300
    digits: 2
    ha_discovery:
      name: Temperature A
      device_class: temperature
      state_class: measurement
      unit_of_measurement: "°C"
```
You need to find the correct `address` of your device by searching in `/sys/bus/w1/devices`.

Bonus: changing resolution of DS18B20
> Writing a value between 9 and 12 to the sysfs w1_slave file will change the
> precision of the sensor for the next readings. This value is in (volatile)
> SRAM, so it is reset when the sensor gets power-cycled.
>
> ...
>
> To store the current precision configuration into EEPROM, the value 0
> has to be written to the sysfs w1_slave file. Since the EEPROM has a limited
> amount of writes (>50k), this command should be used wisely.
>
> https://www.kernel.org/doc/Documentation/w1/slaves/w1_therm

```
echo 12 | sudo tee /sys/bus/w1/devices/28-3c01e076877d/w1_slave
echo 0 | sudo tee /sys/bus/w1/devices/28-3c01e076877d/w1_slave
```
