### ISSUE TITLE
Sensor status keeps switching

### ISSUE THREAD

**Issue by msantic** [flyte/mqtt-io#287]
Hi, could someone help me with this. I'm testing window switch sensor (open/close position) for my alarm central. I can't figure out why when I open the window mqtt keep switching the values True/False/True/False when physically windows remains open? Here is what I get (gif attached)

![mqtt alarm2](https://user-images.githubusercontent.com/314702/196049467-546d574c-9b0b-4b7a-8a47-e77a2ee23f50.gif)

My config.yml for that sensor looks like this:

```
digital_inputs:
  - name: north_window
    module: rpi
    pin: 18
    inverted: yes
    retain: yes
```

**Hardware**
 - Platform: Raspberry Pi
 - Connected hardware:  switch contact sensors

**System:**
 - OS: [e.g. Raspbian]

Thank you
