### ISSUE TITLE
Sensors read but not available in MQTT

### ISSUE THREAD

**Issue by Bluscream** [flyte/mqtt-io#299]
- [x] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Documentation](https://mqtt-io.app/) to see if the information there helps.

**Describe the bug**
I want to share a DHT11 sensor with my HASS IO instance but no analog sensor gets ever broadcasted

**Expected behavior**
`home/timo/input/temperature` and `home/timo/input/humidity` topics becomes available

**Error messages and traceback**
```
blu@automater:/gpio/mqtt $ python3 -m mqtt_io config.yml 
2022-12-15 14:56:32 mqtt_io.server [INFO] Digital input 'automater_digital_input' value changed to False
2022-12-15 14:56:32 mqtt_io.server [INFO] Connecting to MQTT...
2022-12-15 14:56:32 mqtt_io.server [INFO] Read sensor 'temperature' value of 23
2022-12-15 14:56:37 mqtt_io.server [INFO] Connected to MQTT
2022-12-15 14:56:37 mqtt_io.server [INFO] Subscribed to topic: 'home/timo/output/automater_digital_output/set'
2022-12-15 14:56:37 mqtt_io.server [INFO] Subscribed to topic: 'home/timo/output/automater_digital_output/set_on_ms'
2022-12-15 14:56:37 mqtt_io.server [INFO] Subscribed to topic: 'home/timo/output/automater_digital_output/set_off_ms'
2022-12-15 14:56:41 mqtt_io.server [INFO] Read sensor 'humidity' value of 95
2022-12-15 14:56:43 mqtt_io.server [INFO] Read sensor 'temperature' value of 23
2022-12-15 14:56:51 mqtt_io.server [INFO] Read sensor 'humidity' value of 95
2022-12-15 14:56:53 mqtt_io.server [INFO] Read sensor 'temperature' value of 23
```

**Config**
```yaml
mqtt:
  host: home.assistant
  port: 1883
  ha_discovery:
    enabled: yes
  user: 'homeassistant'
  password: ''
  status_payload_running: available
  status_payload_stopped: unavailable
  status_payload_dead: unavailable
  topic_prefix: home/timo

gpio_modules:
  - name: rpi
    module: raspberrypi

sensor_modules:
  - name: dht11_sensor
    module: dht22
    type: DHT11
    pin: 23

sensor_inputs:
  - name: temperature
    module: dht11_sensor
    interval: 10
    digits: 4
    type: temperature
    ha_discovery:
      name: 'Timos Room Temperature'
      device_class: sensor
      state_class: measurement
      unit_of_measurement: "°C"

  - name: humidity
    module: dht11_sensor
    interval: 10
    digits: 4
    type: humidity
    ha_discovery:
      name: 'Timos Room Humidity'
      device_class: sensor
      state_class: measurement
      unit_of_measurement: "%"

digital_inputs:
  - name: automater_digital_input
    module: rpi
    pin: 0

digital_outputs:
  - name: automater_digital_output
    module: rpi
    pin: 0
```

**Hardware**
 - Platform: [e.g. Raspberry Pi, Beaglebone, Banana Pi]
 - Connected hardware:  [e.g. any external GPIO modules, sensors, streams etc.]

|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Raspbian Linux 11     |
|  Webmin version      |     2.010      |
|  Theme version       |     20.11      |
|  Package updates     |     All installed packages are up to date   |

 - Python version: 3.9.2
 - User you're running as: pi
 - Using a virtualenv?: no

<br>

## Mosquitto broker system

version | core-2022.12.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.76-v8
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4949
Installed Version | 1.28.4
Stage | running
Available Repositories | 1227
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | January 5, 2023 at 1:00 AM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | eu-central-1-3.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 9.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.11.2
agent_version | 1.4.1
docker_version | 20.10.19
disk_total | 57.8 GB
disk_used | 5.0 GB
healthy | true
supported | true
board | rpi3-64
supervisor_api | ok
version_api | ok
installed_addons | RPC Shutdown (2.2), File editor (5.4.2), ZeroTier One (0.15.2), Log Viewer (0.14.0), SSH & Web Terminal (13.0.0), Mosquitto broker (6.1.3), MQTT IO (0.1.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 3
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 5, 2022 at 5:26 AM
-- | --
current_recorder_run | December 15, 2022 at 6:16 AM
estimated_db_size | 272.07 MiB
database_engine | sqlite
database_version | 3.38.5

</details>
