### ISSUE TITLE
STATUS change only on ground

### ISSUE THREAD

**Issue by msmthng** [flyte/mqtt-io#309]
- [ ] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Documentation](https://mqtt-io.app/) to see if the information there helps.

**Action description**
sending messages when gpio connected to 3.3v

**Previous attempts**
if i connect ground to the gpio pin i get mqtt messges with on and off paylod.
but if i connect 3.3v (like the sensor iam using is doing it) i don't get a change.

**Error messages and traceback**
```
Paste any error messages and Python traceback if applicable.
```

**Config**
```yaml
mqtt:
  host: *********
  port: 1883
  topic_prefix: octoPrint
gpio_modules:
  - name: raspberrypi
    module: raspberrypi
    cleanup: no
digital_inputs:
  - name: filament_l
    module: raspberrypi
    pin: 14
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no
  - name: filament_r
    module: raspberrypi
    pin: 27
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no

```

**Hardware**
 - Platform: Raspberry Pi
 - Connected hardware:  bigtreetech filament sensor

**System:**
 - OS: raspian with octoprint
 - Python version: 3.7.3
 - User you're running as: pi
 - Using a virtualenv?: no

**Additional context**
