### ISSUE TITLE
Does not run on Raspberry Pi 4 aarch64 architecture using Docker (ModuleNotFoundError: No module named 'RPi' error)

### ISSUE THREAD

**Issue by megapearl** [flyte/mqtt-io#416]
- [V] I have read the [README.md](https://github.com/flyte/pi-mqtt-gpio/blob/develop/README.md) file and visited the [Documentation](https://mqtt-io.app/) to see if the information there helps.

**Describe the bug**
When running by docker at Aarch64 architecture on a raspberry pi 4 it gives an error upon startup.

**Expected behavior**
Should run on aarch64 architecture

**Error messages and traceback**
```
ModuleNotFoundError: No module named 'RPi' error
```

**Config**
```yaml
N/A it does not even start.
```

**Hardware**
 - Platform: [Raspberry Pi4 ]
 - Connected hardware:  [N/A]

**System:**
 - OS: [Linux cupboard-dockers 6.6.56-0-rpi #1-Alpine SMP PREEMPT Fri Oct 11 07:01:26 UTC 2024 aarch64 Linux]
 - Python version: [Python 3.11.10]
 - User you're running as: [root]
 - Using a virtualenv?: [No, running in docker]

**Additional context**
When I add 'RPi-GPIO' to pyproject.toml AND 'pip install RPi.GPIO adafruit-blinka' to Dockerfile using:

        sed -i '/^\[tool.poetry.dependencies\]/a RPi-GPIO = "^0.7.1"' pyproject.toml
        sed -i '/COPY pyproject.toml .\//a RUN pip install RPi.GPIO adafruit-blinka' Dockerfile
 
And rebuild the docker it runs fine on my aarch64 architecture raspberry pi4

**Comment by tkislan** [comment]
I have this same problem

```
gpio_modules:
  - name: raspberrypi
    module: raspberrypi

sensor_modules:
  - name: dht22_sensor
    module: dht22
    type: AM2302
    pin: 4

  - name: mhz19
    module: mhz19
    device: "/dev/ttyAMA0"
    range: 5000

sensor_inputs:
  - name: temperature
    module: dht22_sensor
    interval: 300
    digits: 4
    type: temperature

  - name: humidity
    module: dht22_sensor
    interval: 300
    digits: 4
    type: humidity

  - name: co2_mhz19
    module: mhz19
    interval: 300
    ha_discovery:
      device_class: carbon_dioxide
```

when I specify gpio_module for raspberry, it complaints not having any digital inputs or outputs
```
Config did not validate due to errors in the following sections:                                                                │
│ gpio_modules:                                                                                                                   │
│   raspberrypi:                                                                                                                  │
│   - GPIO module 'raspberrypi' does not have any digital_input or digital_output configs
```

and if I remove it, I get an error that it can't import RPi GPIO

```
  File "/home/mqtt_io/venv/lib/python3.8/site-packages/adafruit_blinka/microcontroller/bcm283x/pin.py", line 5, in <module>
    from RPi import GPIO
ModuleNotFoundError: No module named 'RPi'
```

I don't think that the first case should be an error that shuts down the whole process, and it doesn't run at all .. a warning should be sufficient, as I don't think there would be any problem running with some extra config

or add extra configuration option, to allow to add extra dependencies to be installed

I would like to avoid building a custom Docker image just for this

**Comment by tkislan** [comment]
Hmm, but there might be another problem, because even with manually adding downloading the package, it doesn't report any values
```
/bin/sh -ec "venv/bin/python -m pip install rpi.gpio && venv/bin/python -m mqtt_io /config.yml"
```

**Comment by CarrBen** [comment]
I also had this problem, but I've been able to come up with what seems to be a workaround.

In general, I would very much agree with these quoted coments from @tkislan; with the runtime dependency installation, I think the app needs some way to know that it needs a board/GPIO specific library (`RPi.GPIO`) for a `sensor_module` so that custom Docker Images or extra unused configs (my workaround) aren't required.

EDIT: I had some further thoughts on this; the DHT22 Library from AdaFruit seems to be using some kind of Board detection library to know to import the RPi.GPIO module. If this could be used, I think that would make the options:
* Provide some way to do this via configuration
* Include the Board Detection library as a dependency, call it and `pip install` the appropriate library
* Some kind of two-stage runtime dependency setup, where the first stage installs the Sensor Libtaries (the DHT22 library in my example case), and then does a second pass to see if *those* libraries have any runtime dependencies that need to be installed too (like `RPi.GPIO`).

> when I specify gpio_module for raspberry, it complaints not having any digital inputs or outputs
> 
> ```
> Config did not validate due to errors in the following sections:                                                                │
> │ gpio_modules:                                                                                                                   │
> │   raspberrypi:                                                                                                                  │
> │   - GPIO module 'raspberrypi' does not have any digital_input or digital_output configs
> ```
> 
> and if I remove it, I get an error that it can't import RPi GPIO
> 
> ```
>   File "/home/mqtt_io/venv/lib/python3.8/site-packages/adafruit_blinka/microcontroller/bcm283x/pin.py", line 5, in <module>
>     from RPi import GPIO
> ModuleNotFoundError: No module named 'RPi'
> ```
> 
> I don't think that the first case should be an error that shuts down the whole process, and it doesn't run at all .. a warning should be sufficient, as I don't think there would be any problem running with some extra config
> 
> or add extra configuration option, to allow to add extra dependencies to be installed
> 
> I would like to avoid building a custom Docker image just for this

# Workaround

There are two parts to my workaround; the initial issue where `RPi.GPIO` isn't available, and then once that is working some other permissions issues with Docker

## Can't import `RPi.GPIO`

For the workaround I:
* Added the `raspberrypi` GPIO Module as @tkislan mentions
* Added a `digital_output` on a GPIO Pin that I'm not using, to get around the error about not having input or output configs

This leaves a mqtt-io config.yml like so (I haven't tried adding `ha_discovery` yet, but I will be needing that):
```
gpio_modules:
  - name: rpi
    module: raspberrypi

digital_outputs:
  - name: gpio0
    module: rpi
    pin: 0

sensor_modules:
  - name: dht22_sensor
    module: dht22
    type: dht22
    pin: 4

sensor_inputs:
  - name: temperature
    module: dht22_sensor
    interval: 10
    digits: 4
    type: temperature

  - name: humidity
    module: dht22_sensor
    interval: 10
    digits: 4
    type: humidity
```

## Docker permissions

With that in place, I then get some further errors from the GPIO Library saying that it can only be run on a Raspberry Pi, or `/dev/mem` can't be accessed  and to try running as root.

I ended up with a service like this in my docker-compose.yml
```
  gpio:
    image: flyte/mqtt-io
    cap_drop:
      - ALL  # DHT22 via Pi GPIO seems to run fine without any CAPs
    security_opt:
      # Needed to access /proc/device-tree/system/linux,revision
      # So the GPIO Library can confirm it's running on a Pi
      # This could allow a process in the container to write to /proc, if it can elevate
      # But I think this should still be better than privileged mode
      # Maybe apparmor could be used to lock things down more precisely?
      - systempaths=unconfined
    group_add:
      # Add the mqtt_io user (that the process runs as) to the Host GPIO Group (provided by env var here)
      # Without this, filesystem permissions inside the container will prevent access to GPIO
      - ${GPIO_GID}
    volumes:
      - ${CONFIG_DIR}/gpio.yml:/config.yml
    devices:
      #- /dev/gpiochip0  # might be needed to access the Pi GPIO, but seems OK commented out
      - /dev/gpiomem  # Needed for the GPIO Library to check for GPIO access
```

If I get some time, I will try to raise a PR with some updates to the Doc page about running in Docker.

With both of these, that gives me values in the Docker logs:
```
gpio-1  | 2025-09-11 21:34:58 mqtt_io.server [INFO] Read sensor 'humidity' value of 56.0
gpio-1  | 2025-09-11 21:34:59 mqtt_io.server [INFO] Read sensor 'temperature' value of 23.0
```
