### ISSUE TITLE
module `ds18b` dynamic configuration with object as output

### ISSUE THREAD

**Issue by petrsx** [flyte/mqtt-io#420]
My plan is to create configuration template (universal) so hardcoding value in config or scripting around may be not so ideal. 

Is possible the to remove `address` from `sensor_modules` and the `sensor_inputs` will produce output as array (all sensors values) and we may use HA (or any other automation) to filter it out?

Something like that

```json
[
    {
        "id": 0,
        "temp": 21.75,
        "address": "1a19709614ff"
    },
    {
        "id": 1,
        "temp": 20.62,
        "address": "1a19709614fe"
    }
]
```

Please check this script which is doing exactly that: https://github.com/Pekaway/VAN_PI/blob/main/VanPi-Core-OS/data/ds18b20_py/ds18b20.py

```yaml
sensor_modules:
  - name: ds18b20
    module: ds18b
    type: DS18B20

sensor_inputs:
  - name: temperatures
    module: ds18b20
    interval: 5
    digits: 2
```

Alternative can be to move `address` from `sensor_modules` to `sensor_inputs`? Then it will be easier to autogenerate the `sensor_inputs`

So instead of this

```yaml
sensor_modules:
  - name: ds18b20
    module: ds18b
    type: DS18B20
    address: "1a19709614ff"

sensor_inputs:
  - name: temp1
    module: ds18b20
    interval: 5
    digits: 2
```

To have this

```yaml
sensor_modules:
  - name: ds18b20
    module: ds18b
    type: DS18B20

sensor_inputs:
  - name: temp1
    module: ds18b20
    interval: 5
    digits: 2
    address: "1a19709614ff"
```

Thank you
