### ISSUE TITLE
Two piface2 modules on same board

### ISSUE THREAD

**Issue by ghost** [flyte/mqtt-io#49]
Would it be possible to add support for two piface2 modules? At the moment only the first piface2 seems to be supported, and there does not seem to be an option to select the second one on a different address. With the address jumpers 4 modules in total are allowed on the same Pi.

I would like something like this:

```
gpio_modules:
  - name: piface2-1
    module: piface2
    chip_select: 0

  - name: piface2-2
    module: piface2
    chip_select: 1
```
