### ISSUE TITLE
Garage door with 2 sensors

### ISSUE THREAD

**Issue by iondarie** [flyte/mqtt-io#77]
Hello,

I have a garage door that has 2 sensors, one at each end of the line.

One activates when the door is fully open and one when it is fully closed.

Can the status of these 2 sensors be read and posted under the same topic?

Thank you

**Comment by BenjiU** [comment]
Hi,

I think, that this is not possible right now. 
The name of the sensor is used as "topic":
```
digital_inputs:
  - name: button
    module: raspberrypi
    pin: 21
    on_payload: "ON"
    off_payload: "OFF"
    pullup: no
    pulldown: yes
```

and in the code the "name" is currently used as "index" in LAST_STATES dict:
```
   for in_conf in digital_inputs:
        print (in_conf)
        initialise_digital_input(in_conf, GPIO_MODULES[in_conf["module"]])
        LAST_STATES[in_conf["name"]] = None
```
So you can't insert two sensors with the same name/topic.

If you're still working on your garage door, maybe we can help you to find a different solution. Greetings.
