### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by nicoolaro** [flyte/mqtt-io#90]
I can't get this working on docker.
i tried 

> sudo docker run -ti --rm -v /home/pi/config.yml:/config.yml --privileged flyte/mqtt-gpio
also

> sudo docker run -ti --rm -v config.yml:/config.yml --privileged flyte/mqtt-gpio

my config is in home/pi folder
```
mqtt:
  discovery: yes
  # The following is optional (homeassistant is the default)
  discovery_prefix: homeassistant
  # Optional too, but change to whatever you like
  discovery_name: MQTT GPIO

  host: 192.168.1.10
  port: 1883
  user: ****
  password: ***
  topic_prefix: pizerocam
  status_topic: status
  status_payload_running: running
  status_payload_stopped: stopped
  status_payload_dead: dead
gpio_modules:
  - name: raspberrypi
    module: raspberrypi
    cleanup: yes

digital_inputs:
  - name: doorbell
    module: raspberrypi
    pin: 3
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no
  - name: doorbell_led
    module: raspberrypi
    pin: 2
    on_payload: "ON"
    off_payload: "OFF"
    pullup: yes
    pulldown: no
```

i get error : standard_init_linux.go:211: exec user process caused "exec format error"
Am i following corect installation steps for docker (docker is installed on my Pi Zero W)
