### ISSUE TITLE
Proposed addition of serial port (and other streaming hardware)

### ISSUE THREAD

**Issue by ChrisEAlfred** [flyte/mqtt-io#95]
Brilliant work - I like your coding style.

I was thinking of contributing support for streaming hardware - initially serial ports (via PySerial).

Does this schema look ok to you:

```
stream_modules:
  - name: comms
    module: streamserial
    device: /dev/ttyS0
    baud: 115200
    cleanup: yes

stream_reads:
  - name: serialrx
    module: comms
    interval: 0.25

stream_writes:
  - name: serialtx
    module: comms
```

**Comment by BenjiU** [comment]
Hey, I like that: I have a smart meter, that gives me a serial output and is currently parsed in perl, but i want to move it to this, for example. So i would send the raw data via mqtt and parse it somewhere else.
What does your interval 0.25 mean? 
My smartmeter gives an output every second: a few hundred bytes.
So we would have a background task collecting the data and send it every 0.25 sec or if there is a pause? I would like to collect the whole data first and not send a split data in two frames.

**Comment by ChrisEAlfred** [comment]
The 0.25 is the stream receive polling interval in seconds.

I already have a working version - testing happily here.

As for your serial case, in past systems we have used an 'idle time' concept (also called idle line).
You buffer the data until there is a pause for more than the idle time, then send the buffer. Any character triggers the start of buffer reading.

So we could add an optional parameter like:

```
stream_reads:
  - name: serialrx
    module: comms
    interval: 0.25
    idlebuffer: yes   # optional, default to "no"
```

idlebuffer: yes will buffer received data until there is one interval of no more received data and the data will be sent in one go.
