### ISSUE TITLE
Example of pin address for BeagleBone Black

### ISSUE THREAD

**Issue by jfiger** [flyte/mqtt-io#96]
I did not find an example of pin address for BeagleBone Black in the documentation.
 pin: P8_7 is accepted  but not working for digital output. No error message.
BTW Input pins are working.

```
config.yml
mqtt:
  host: 192.168.10.123
  port: 1883
  user: "mqtt"
  password: "mqtt"
  topic_prefix: home/bbb

gpio_modules:
  - name: beaglebone
    module: beaglebone

digital_outputs:
  - name: lights
    module: beaglebone
    pin: P8_7
    on_payload: "ON"
    off_payload: "OFF"
    initial: low  # This optional value controls the initial state of the pin 
    retain: yes # This option value controls if the message is retained. 
```
